Objectstorage:
  S3:
    UserBucket: baktauserdata2
    DBBucket: baktadbs
    BaseKey: data/dev
    Endpoint: https://s3.computational.bio.uni-giessen.de
K8sNamespace: "bakta"
WorkflowTemplate: "bakta-job-1.2.2"
Version:
  Tool: "1.1.1"
  DB: "3.0.0"