Objectstorage:
  S3:
    UserBucket: baktauserdata
    DBBucket: baktadbs
    BaseKey: data/dev
Database:
  Backend: SQLite
  SQLite:
    Path: /tmp
K8sNamespace: "bakta-dev"
UpdateService:
  Name: baktawebbackend
  Port: "8081"
Testing: true