use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Bakta Web Service API",
        description = "Combined OpenAPI document for the stable V1 Bakta API, the extensible V2 workflow API, and observability endpoints.",
        license(name = "MIT", url = "https://opensource.org/license/mit/")
    ),
    servers(
        (url = "/", description = "Current deployment")
    ),
    tags(
        (name = "v1", description = "Stable V1 API for the original Bakta genome annotation workflow."),
        (name = "v2", description = "V2 API for multiple workflow kinds including Bakta Proteins and Baktfold."),
        (name = "observability", description = "Operational endpoints such as Prometheus metrics.")
    ),
    paths(
        crate::v1::api_paths::delete_job,
        crate::v1::api_paths::job_logs,
        crate::v1::api_paths::init_job,
        crate::v1::api_paths::list_jobs,
        crate::v1::api_paths::query_result,
        crate::v1::api_paths::start_job,
        crate::v1::api_paths::version,
        crate::v2::api_paths::workflows,
        crate::v2::api_paths::init_job,
        crate::v2::api_paths::list_jobs,
        crate::v2::api_paths::query_result,
        crate::v2::api_paths::start_job,
        crate::v2::api_paths::job_logs,
        crate::v2::api_paths::delete_job,
        crate::v2::api_paths::version,
        crate::metrics::metrics,
    ),
    components(schemas(
        crate::api_structs::Job,
        crate::api_structs::InitRequest,
        crate::api_structs::InitResponse,
        crate::api_structs::RepliconTableType,
        crate::api_structs::ListRequest,
        crate::api_structs::ListResponse,
        crate::api_structs::JobStatusEnum,
        crate::api_structs::JobStatus,
        crate::api_structs::FailedJobStatus,
        crate::api_structs::FailedJobStatusEnum,
        crate::api_structs::ResultFiles,
        crate::api_structs::ResultResponse,
        crate::api_structs::StartRequest,
        crate::api_structs::JobConfig,
        crate::api_structs::DermType,
        crate::api_structs::VersionResponse,
        crate::v2::api_structs::WorkflowKind,
        crate::v2::api_structs::ResultKind,
        crate::v2::api_structs::UploadKind,
        crate::v2::api_structs::DermType,
        crate::v2::api_structs::StageStatus,
        crate::v2::api_structs::JobStatus,
        crate::v2::api_structs::FailedJobStatusKind,
        crate::v2::api_structs::JobReference,
        crate::v2::api_structs::FailedJobStatus,
        crate::v2::api_structs::UploadDescriptor,
        crate::v2::api_structs::UploadLink,
        crate::v2::api_structs::WorkflowDescriptorResponse,
        crate::v2::api_structs::V2InitRequest,
        crate::v2::api_structs::V2InitResponse,
        crate::v2::api_structs::EmptyConfig,
        crate::v2::api_structs::BaktaV2Config,
        crate::v2::api_structs::V2StartRequest,
        crate::v2::api_structs::WorkflowStartConfig,
        crate::v2::api_structs::V2ListRequest,
        crate::v2::api_structs::V2JobStatus,
        crate::v2::api_structs::V2ListResponse,
        crate::v2::api_structs::BaktaResultFiles,
        crate::v2::api_structs::BaktaProteinsResultFiles,
        crate::v2::api_structs::BaktfoldResultFiles,
        crate::v2::api_structs::V2ResultFiles,
        crate::v2::api_structs::V2ResultResponse,
        crate::v2::api_structs::StageLog,
        crate::v2::api_structs::V2LogsResponse,
        crate::v2::api_structs::V2VersionResponse,
    ))
)]
pub struct BaktaServiceApi;
